### ISSUE TITLE
Discussion: Move this adapter to The PHP League.

### ISSUE THREAD

**Issue by frankdejonge** [twistor/flysystem-memory-adapter#1]
Hi @twistor,

My buddy @reinink came to me with the question of a InMemory adapter, also mentioned this repository as a good base. After some chitchat we figured this adapter would actually be pretty close to what we'd want to see.

As such, it could be a good move to move this repository to the php league. You'd then be invited as the maintainer of the package. I've got some minor "issues" (quotes intended) with the design, but those are very minor and probably eliminated within an hours work.

What do you think of this proposal?

**Comment by reinink** [comment]
Yeah, this would be great!

An in-memory adapter actually has uses outside of testing even. For example, with my [Glide](https://github.com/thephpleague/glide) project, some folks don't ever want the cached images to hit the local filesystem (for performance reasons), but instead just want Glide to spit out the image in the response, and they use something like Varnish to cache it. This adapter makes this possible, since the images are created, saved in the in-memory adapter, and then destroyed when the request finishes. Very nice and clean.

**Comment by twistor** [comment]
Absolutely, I'm fine with moving this. I had thought about opening a pull request before, but didn't think it was quite done yet, ha.

Do you want to create issues here, and I can knock them out, or move it fix things over there?

One thing I was considering was using tmp files or memory streams to keep memory usage down, but then I was concerned about too many open file handles.

**Comment by reinink** [comment]
Excellent!

By the way, I wouldn't use temp files, as the big benefit to this adapter is that it doesn't hit the file system. If someone is using it, they should be aware of the amount of stuff their putting in memory.

**Comment by twistor** [comment]
I agree with that. I was thinking of php://temp streams, but that's a different adapter.

In fact, if this is going to be used as a real adapter, there's some things we can simplify. I initially wrote it to be very strict, for testing purposes, but if it's going to be used as a real adapter, we can relax some of the checks, and just rely on the Filesystem's checks.

We can also make some performance improvements, making timestamps optional, and delaying mimetype checking.

Should probably remove the createFromPath() and createFromFilesystem() methods as well.

**Comment by frankdejonge** [comment]
@twistor just as a quick discussion point. I think the createFromX stuff should be moved to some kind of builder class. The adapter shouldn't know how to build itself. Which also, when used in a non-test setup will make things more testable (weird, I know). What do you think?

**Comment by twistor** [comment]
Yup! See https://github.com/twistor/flysystem-memory-adapter/tree/league-migration

**Comment by reinink** [comment]
Hey! Not try to push at all, I'm just curious where this is at? Is the adapter ready to be moved to the Flysystem repository yet? Would you like me to setup a new repo for this? Let me know, thanks! :+1:

**Comment by twistor** [comment]
I think the adapter is ready. The league-migration branch has the updated code, tests, and the namespace changed. Assuming league/flysystem-memory is what the new repo will be, it should be all set.

As to @frankdejonge comments about createFromX() stuff, I've just removed it for now. I have a thought about creating an actual test adapter but that's a different thing. It can always be added back later if needed. Cloning filesystems could very well be a whole different project.

I plan to keep this repo here for a while, I'll deprecate it some how, but I know there's at least one other project depending on it.

**Comment by reinink** [comment]
Okay, sweet. I agree with keeping this repo around for a while, and then just marking it as abandoned on Packagist. Maybe I'll get the process going here. I'll download your branch locally, add any necessary League stuff, and then push up to a new repo on the League side. That saves us from having to do any aliasing/redirects. Is that cool with you?

**Comment by twistor** [comment]
Sounds good to me!

**Comment by reinink** [comment]
Here we go!

https://github.com/thephpleague/flysystem-memory

**Comment by twistor** [comment]
I'll sort out the rest on this end.

**Comment by reinink** [comment]
Good stuff. Also, you should have received an invite to that repo on the League side.

**Comment by twistor** [comment]
Yup. Do I create the new packagist project?

**Comment by reinink** [comment]
I already asked Frank on Twitter to see if he wanted to, just because I think he manages all the Flysystem adapters on there. Maybe wait until I hear back from him on that?

**Comment by twistor** [comment]
Works for me.

**Comment by reinink** [comment]
Okay, so Frank has added this to [Packagist](https://packagist.org/packages/league/flysystem-memory) and Scrutinizer.

**Comment by reinink** [comment]
Added to the Flysystem documentation:

http://flysystem.thephpleague.com/adapter/memory/
